### ISSUE TITLE
NHS should use British English

### ISSUE THREAD

**Issue by timcoote** [nhs-r-community/open-analytics-resources#32]
I've not submitted a PR for this as I can see that the point could be debated.

Line 23 of `_quarto.yml`:
`
      NHS-R Community makes all of their materials publicly available under open source licenses
`
should be
`
      NHS-R Community makes all of their materials publicly available under open source licences
`
as the word 'licences' in this context is a noun, not a verb. As NHS is a UK entity, I'm assuming that its language should be British English.

**Comment by Lextuga007** [comment]
Yes! Agreed and this is mentioned in full https://tools.nhsrcommunity.com/open-code.html#language with the NHS-R Way https://nhsrway.nhsrcommunity.com/style-guides.html#language. Thanks for picking this up.
